version: "3"

services:
  web:
    image: nginx:alpine
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
        - "${APP_PORT:-80}:80"
    volumes:
       - ".:/public_html"
       - "./conf.d:/etc/nginx/conf.d"
       - "/etc/localtime:/etc/localtime"

    networks:
      - nginxphp

  php:
    image: php:8.1.5-fpm-alpine
    restart: always
    volumes:
      - .:/public_html
    expose:
      - 9000
    networks:
      - nginxphp

networks:
  nginxphp:
